name = "vfncvt.xu.f.w"
format = "vd,vs2,vm"

[tests]
sew64 = [
    ["0x7ff8000000000000"], # Quiet NaN
    ["0x7ff8000000000001"], # Quiet NaN "1"
    ["0x7ff8000000000002"], # Quiet NaN "2"
    ["0x7ff4000000000000"], # Signaling NaN
    ["0x7ff0000000000000"], #  Inf
    ["0xfff0000000000000"], # -Inf
    ["0x0000000000000000"], #  0
    ["0x8000000000000000"], # -0
    ["0xc00921f9f01b866e"], # -3.14159
    ["0x400921f9f01b866e"], #  3.14159
    ["0x0000000000000001"], # Subnormal
    ["0x000fffffffffffff"], # Submornal
]
