name = "vfrsqrt7.v"
format = "vd,vs2,vm"

supported_zve = ["Zve32f", "Zve64f", "Zve64d"]

[tests]
sew32 = [
    [0x40490fda], # 3.1415926
    [0x461c4000], # 10000
    [0xbf800000], # -1
    [0x432b0000], # 171.0
    [0x342ca6fe], # 1.60795e-7
]

sew64 = [
    ["0x400921fb40000000"], # 3.1415926
    ["0x40c3880000000000"], # 10000
    ["0xbff0000000000000"], # -1
    ["0x4065600000000000"], # 171.0
    ["0x3e8594dfc0000000"], # 1.60795e-7
]