name = "vfsgnjx.vv"
format = "vd,vs2,vs1,vm"

[tests]
fsew32 = [
    [ 1.0,  1.0],
    [ 1.0, -1.0],
    [ 1.0, -0.0],
    [ 1.0,  0.0],
    [-1.0, -0.0],
    [-1.0,  0.0],
    [-0.0,  0.0],
    [ 0.0, -0.0],
    [-3.14159265,  0.0001],
    [-3.14159265, -0.0001]
]
fsew64 = [
    [ 1.0,  1.0],
    [ 1.0, -1.0],
    [ 1.0, -0.0],
    [ 1.0,  0.0],
    [-1.0, -0.0],
    [-1.0,  0.0],
    [-0.0,  0.0],
    [ 0.0, -0.0],
    [-3.14159265,  0.0001],
    [-3.14159265, -0.0001]
]
