name = "vmfgt.vf"
fp = true
format = "vd,vs2,fs1,vm"

[tests]
fsew32 = [
    ["2.5",                     "1.0"],
    ["-1235.1",                 "1.1"],
    ["3.14159265",              "0.00000001"],
    ["1.1",                     "-1235.1"],
    ["-1.0",                    "-2.0"],
    ["nan",                     "-nan"],
    ["inf",                     "-inf"],
    ["quiet_nan",               "signaling_nan"],
    ["smallest_nonzero_float",  "largest_subnormal_float"],
    ["smallest_normal_float",   "max_float"],
    ["-smallest_nonzero_float", "-largest_subnormal_float"],
    ["-smallest_normal_float",  "-max_float"]
]
fsew64 = [
    ["2.5",                     "1.0"],
    ["-1235.1",                 "1.1"],
    ["3.14159265",              "0.00000001"],
    ["1.1",                     "-1235.1"],
    ["-1.0",                    "-2.0"],
    ["nan",                     "-nan"],
    ["inf",                     "-inf"],
    ["quiet_nan",               "signaling_nan"],
    ["smallest_nonzero_float",  "largest_subnormal_float"],
    ["smallest_normal_float",   "max_float"],
    ["-smallest_nonzero_float", "-largest_subnormal_float"],
    ["-smallest_normal_float",  "-max_float"]
]
