name = "vsll.vi"
format = "vd,vs2,uimm,vm"

[tests]
base = [
    [0x0, 0x0],
    [0x1, 0x2],
    [0x3, 0xf]
]
sew8 = [
    [0x1f, 0x00],
    [0x1,  0xff],
    [0x1,  0x7f],
    [0x1f, 0xff]
]
sew16 = [
    [0x1f, 0x0000],
    [0x1,  0xffff],
    [0x1,  0x7fff],
    [0x1f, 0xffff]
]
sew32 = [
    [0x1f, 0x00000000],
    [0x1,  0xffffffff],
    [0x1,  0x7fffffff],
    [0x1f, 0xffffffff]
]
sew64 = [
    ["0x1f", "0x0000000000000000"],
    ["0x1",  "0xffffffffffffffff"],
    ["0x1",  "0x7fffffffffffffff"],
    ["0x1f", "0xffffffffffffffff"]
]
