name = "vsmul.vv"
format = "vd,vs2,vs1,vm"

[tests]
base = [
    [0x0, 0x0],
    [0x1, 0x1],
    [0x3, 0x7]
]
sew8 = [
    [0x7e, 0xb7],
    [0xc0, 0xb7],
    [0x00, 0x80],
    [0x80, 0x00],
    [0x80, 0x80],
    [0xab, 0x7d],
    [0x7d, 0xab],
    [0xff, 0xff],
    [0xff, 0xff],
    [0xff, 0x01],
    [0x01, 0xff]
]
sew16 = [
    [0x7e00, 0x6db7],
    [0x7fc0, 0x6db7],
    [0x0000, 0x8000],
    [0x8000, 0x0000],
    [0x8000, 0x8000],
    [0xaaab, 0xfe7d],
    [0xfe7d, 0xaaab],
    [0xff00, 0xff00],
    [0xffff, 0xffff],
    [0xffff, 0x0001],
    [0x0001, 0xffff]
]
sew32 = [
    [0x00007e00, 0xb6db6db7],
    [0x00007fc0, 0xb6db6db7],
    [0x00000000, 0xffff8000],
    [0x80000000, 0x00000000],
    [0x80000000, 0xffff8000],
    [0xaaaaaaab, 0x0002fe7d],
    [0x0002fe7d, 0xaaaaaaab],
    [0xff000000, 0xff000000],
    [0xffffffff, 0xffffffff],
    [0xffffffff, 0x00000001],
    [0x00000001, 0xffffffff]
]
sew64 = [
    ["0x0000000000007e00", "0x6db6db6db6db6db7"],
    ["0x0000000000007fc0", "0x6db6db6db6db6db7"],
    ["0x0000000000000000", "0xffffffffffff8000"],
    ["0xffffffff80000000", "0x0000000000000000"],
    ["0xffffffff80000000", "0xffffffffffff8000"],
    ["0xaaaaaaaaaaaaaaab", "0x000000000002fe7d"],
    ["0x000000000002fe7d", "0xaaaaaaaaaaaaaaab"]
]
