name = "vsub.vv"
format = "vd,vs2,vs1,vm"

[tests]
base = [
    [0x0, 0x0],
    [0x1, 0x2],
    [0x3, 0xf]
]
sew8 = [
    [0xf8, 0x00],
    [0x00, 0xf8],
    [0xf8, 0x08],
    [0x7f, 0x00],
    [0x00, 0x7f],
    [0x7f, 0x07],
    [0x7f, 0x01],
    [0xff, 0x00],
    [0x00, 0xff],
    [0xff, 0x01],
    [0x01, 0xff],
    [0xff, 0xff],
    [0xff, 0x00]
]
sew16 = [
    [0xfff8, 0x0000],
    [0x0000, 0xfff8],
    [0xfff8, 0x0008],
    [0x7fff, 0x0000],
    [0x0000, 0x7fff],
    [0x7fff, 0x0007],
    [0x7fff, 0x0001],
    [0xffff, 0x0000],
    [0x0000, 0xffff],
    [0xffff, 0x0001],
    [0x0001, 0xffff],
    [0xffff, 0xffff],
    [0xffff, 0x0000]
]
sew32 = [
    [0xfffffff8, 0x00000000],
    [0x00000000, 0xfffffff8],
    [0xfffffff8, 0x00000008],
    [0x7fffffff, 0x00000000],
    [0x00000000, 0x7fffffff],
    [0x7fffffff, 0x00000007],
    [0x7fffffff, 0x00000001],
    [0xffffffff, 0x00000000],
    [0x00000000, 0xffffffff],
    [0xffffffff, 0x00000001],
    [0x00000001, 0xffffffff],
    [0xffffffff, 0xffffffff],
    [0xffffffff, 0x00000000]
]
sew64 = [
    ["0x0000000000000000", "0xffffffffffff8000"],
    ["0xffffffff80000000", "0x0000000000000000"],
    ["0xffffffff80000000", "0xffffffffffff8000"],
    ["0x0000000000000000", "0x0000000000007fff"],
    ["0x000000007fffffff", "0x0000000000000000"],
    ["0x000000007fffffff", "0x0000000000007fff"],
    ["0xffffffff80000000", "0x0000000000007fff"],
    ["0x000000007fffffff", "0xffffffffffff8000"],
    ["0x0000000000000000", "0xffffffffffffffff"],
    ["0xffffffffffffffff", "0x0000000000000001"],
    ["0xffffffffffffffff", "0xffffffffffffffff"]
]
