name = "vsuxseg6ei64.v"
format = "vs3,(rs1),vs2,vm"

[tests]
base = [
    [0x0],
    [0x1],
    [0x2],
    [0xf]
]
sew64 = [
    ["0x7fffffffffffffff"],
    ["0xfffffffffffffff8"],
    ["0xffffffffffffffff"]
]
